name: CI/CD Pipeline

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # required so the job can request an OIDC token from GitHub
      contents: read
    steps:
      - name: Checkout project repository
        uses: actions/checkout@v7
      - name: Checkout upstream textbook data
        uses: actions/checkout@v7
        with:
          repository: pubuyun/ChinaTextbook
          ref: 65054ef0e8323e772dc99e6eddba9715672d0f91
          path: data
          fetch-depth: 1
          sparse-checkout: |
            小学
            小学（五•四学制）
            初中
            初中（五•四学制）
            高中
      - name: Install the hf CLI
        run: |
          curl -LsSf https://hf.co/cli/install.sh | bash
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build and run PDF merger
        run: |
          rustc -O main.rs -o process-pdfs
          ./process-pdfs
      - name: Display output directory tree
        run: tree -I '.git' --dirsfirst data
      - name: Upload to Hugging Face
        env:
          HF_OIDC_RESOURCE: datasets/RainPPR/china-textbook-2021-hf
        run: hf upload datasets/RainPPR/china-textbook-2021-hf ./data . --commit-message "Publish from ${GITHUB_SHA::7}"
